server:
  port: 80

app:
  host:
    name: ${HELPER_FILE_SHARING:file-sharing.kazatu.kz}
    protocol: http

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB