server:
  port: 80

app:
  host:
    name: ${HELPER_FILE_SHARING_HOST_NAME:file-sharing.kazatu.kz}
    protocol: ${HELPER_FILE_SHARING_HOST_PROTOCOL:http}

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB