server:
  port: 80

app:
  folder: ${HELPER_FILE_SHARING_CONTENT_FOLDER:content}
  host:
    name: ${HELPER_FILE_SHARING_HOST_NAME:file-sharing.kazatu.kz}
    protocol: ${HELPER_FILE_SHARING_HOST_PROTOCOL:http}

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: ${HELPER_FILE_SHARING_MAX_FILE_SIZE:100MB}
      max-request-size: ${HELPER_FILE_SHARING_MAX_REQUEST_SIZE:100MB}